if(NOT SPIRV_CROSS_LIBRARY)
  find_path(SPIRV_CROSS_INCLUDE_DIR "spirv_cross/spirv_cross.hpp")
  find_library(SPIRV_CROSS_LIBRARY core
    NAMES
      spirv-cross-core
    PATH_SUFFIXES
      lib
  )
endif()

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPIRV_CROSS REQUIRED_VARS
  SPIRV_CROSS_LIBRARY SPIRV_CROSS_INCLUDE_DIR)

mark_as_advanced(SPIRV_CROSS_INCLUDE_DIRS)
mark_as_advanced(SPIRV_CROSS_LIBRARIES)

if(SPIRV_CROSS_FOUND)
  set(SPIRV_CROSS_INCLUDE_DIRS ${SPIRV_CROSS_INCLUDE_DIR})
  set(SPIRV_CROSS_LIBRARIES ${SPIRV_CROSS_LIBRARY})

  if(NOT TARGET SPIRV::Cross)
    add_library(SPIRV::Cross UNKNOWN IMPORTED)
    set_target_properties(SPIRV::Cross PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${SPIRV_CROSS_INCLUDE_DIRS}")
    set_property(TARGET SPIRV::Cross APPEND PROPERTY
      IMPORTED_LOCATION "${SPIRV_CROSS_LIBRARY}")
  endif()
endif()
