if(NOT SPIRV_CROSS_CORE_LIBRARY)
  find_path(SPIRV_CROSS_CORE_INCLUDE_DIR "spirv_cross/spirv_cross.hpp")
  find_library(SPIRV_CROSS_CORE_LIBRARY_DEBUG
    NAMES
      spirv-cross-core-d
      spirv-cross-core
    PATH_SUFFIXES
      lib
  )
  find_library(SPIRV_CROSS_CORE_LIBRARY_RELEASE
    NAMES
      spirv-cross-core
    PATH_SUFFIXES
      lib
  )
  set(SPIRV_CROSS_CORE_LIBRARY
    debug ${SPIRV_CROSS_CORE_LIBRARY_DEBUG}
    optimized ${SPIRV_CROSS_CORE_LIBRARY_RELEASE}
  )
endif()

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPIRV_CROSS_CORE REQUIRED_VARS
  SPIRV_CROSS_CORE_LIBRARY SPIRV_CROSS_CORE_INCLUDE_DIR)

mark_as_advanced(SPIRV_CROSS_CORE_INCLUDE_DIRS)
mark_as_advanced(SPIRV_CROSS_CORE_LIBRARIES)

if(SPIRV_CROSS_CORE_FOUND)
  set(SPIRV_CROSS_CORE_INCLUDE_DIRS ${SPIRV_CROSS_CORE_INCLUDE_DIR})
  set(SPIRV_CROSS_CORE_LIBRARIES ${SPIRV_CROSS_CORE_LIBRARY})

  if(NOT TARGET SpirVCross::core)
    add_library(SpirVCross::core UNKNOWN IMPORTED)
    set_target_properties(SpirVCross::core PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${SPIRV_CROSS_CORE_INCLUDE_DIRS}")

    set_property(TARGET SpirVCross::core APPEND PROPERTY
      IMPORTED_CONFIGURATIONS RELEASE)
    set_property(TARGET SpirVCross::core APPEND PROPERTY
      IMPORTED_CONFIGURATIONS DEBUG)

    if(SPIRV_CROSS_CORE_LIBRARY_DEBUG AND SPIRV_CROSS_CORE_LIBRARY_RELEASE)
      set_target_properties(SpirVCross::core PROPERTIES
        IMPORTED_LOCATION_DEBUG "${SPIRV_CROSS_CORE_LIBRARY_DEBUG}"
        IMPORTED_LOCATION_RELEASE "${SPIRV_CROSS_CORE_LIBRARY_RELEASE}"
      )
    else()
      set_target_properties(SpirVCross::core PROPERTIES
        IMPORTED_LOCATION "${SPIRV_CROSS_CORE_LIBRARY_RELEASE}"
      )
    endif()
  endif()
endif()

################################################################################

if(NOT SPIRV_CROSS_UTIL_LIBRARY)
  find_path(SPIRV_CROSS_UTIL_INCLUDE_DIR "spirv_cross/spirv_cross.hpp")
  find_library(SPIRV_CROSS_UTIL_LIBRARY_DEBUG
    NAMES
      spirv-cross-util-d
      spirv-cross-util
    PATH_SUFFIXES
      lib
  )
  find_library(SPIRV_CROSS_UTIL_LIBRARY_RELEASE
    NAMES
      spirv-cross-util
    PATH_SUFFIXES
      lib
  )
  set(SPIRV_CROSS_UTIL_LIBRARY
    debug ${SPIRV_CROSS_UTIL_LIBRARY_DEBUG}
    optimized ${SPIRV_CROSS_UTIL_LIBRARY_RELEASE}
  )
endif()

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SPIRV_CROSS_UTIL REQUIRED_VARS
  SPIRV_CROSS_UTIL_LIBRARY SPIRV_CROSS_UTIL_INCLUDE_DIR)

mark_as_advanced(SPIRV_CROSS_UTIL_INCLUDE_DIRS)
mark_as_advanced(SPIRV_CROSS_UTIL_LIBRARIES)

if(SPIRV_CROSS_UTIL_FOUND)
  set(SPIRV_CROSS_UTIL_INCLUDE_DIRS ${SPIRV_CROSS_UTIL_INCLUDE_DIR})
  set(SPIRV_CROSS_UTIL_LIBRARIES ${SPIRV_CROSS_UTIL_LIBRARY})

  if(NOT TARGET SpirVCross::util)
    add_library(SpirVCross::util UNKNOWN IMPORTED)
    set_target_properties(SpirVCross::util PROPERTIES
      INTERFACE_INCLUDE_DIRECTORIES "${SPIRV_CROSS_UTIL_INCLUDE_DIRS}")

    set_property(TARGET SpirVCross::util APPEND PROPERTY
      IMPORTED_CONFIGURATIONS RELEASE)
    set_property(TARGET SpirVCross::util APPEND PROPERTY
      IMPORTED_CONFIGURATIONS DEBUG)

    if(SPIRV_CROSS_UTIL_LIBRARY_DEBUG AND SPIRV_CROSS_UTIL_LIBRARY_RELEASE)
      set_target_properties(SpirVCross::util PROPERTIES
        IMPORTED_LOCATION_DEBUG "${SPIRV_CROSS_UTIL_LIBRARY_DEBUG}"
        IMPORTED_LOCATION_RELEASE "${SPIRV_CROSS_UTIL_LIBRARY_RELEASE}"
      )
    else()
      set_target_properties(SpirVCross::util PROPERTIES
        IMPORTED_LOCATION "${SPIRV_CROSS_UTIL_LIBRARY_RELEASE}"
      )
    endif()
  endif()
endif()
